[package]
name = "vvnetwork-test"
version = "0.1.0"
edition = "2021"

[dependencies]
fast-socks5 = "0.8.1"
anyhow = "1.0.68"
tokio = { version = "1.24.2", features = ["full"] }
chrono = "0.4.23"
log = "0.4"
env_logger = "0.10.0"