[package]
name = "whois_find"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whois-rust = "1.5.1"
serde_json = "1.0.91"